### ISSUE TITLE
[Bug] Circle above visualization

### ISSUE THREAD

**Issue by lndgalante** [statecharts/xstate-viz#9]
I tried `xstate-viz` different versions with CRA and CodeSandbox and I always get this issue:

<img width="408" alt="captura de pantalla 2019-02-25 a la s 09 58 34" src="https://user-images.githubusercontent.com/2475912/53339094-17880580-38e4-11e9-8a47-570da758a90f.png">

**Comment by lndgalante** [comment]
@davidkpiano I just fixed copying the styles from https://statecharts.github.io/xstate-viz

Maybe a possible solution is to add the following styles using [createGlobalStyle](https://www.styled-components.com/docs/api#createglobalstyle)

```css
body {
  margin: 0;
  padding: 0;
  font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans,
    Helvetica Neue, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

code {
  font-family: source-code-pro, Menlo, Monaco, Consolas, Courier New, monospace;
}

*,
:after,
:before {
  box-sizing: border-box;
  position: relative;
}

body,
html {
  width: 100%;
  margin: 0;
  padding: 0;
}

#root,
body,
html {
  height: 100%;
}
```
